name: checkout project to overflow
on: 
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCOUNT_TOKEN }}
      - name: show pwd
        run: pwd
      - name: show dir info
        run: ls -l
      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Build with Maven
        run: mvn clean install -DskipTest
