# 这定义工作流的名称，它将显示在 GitHub 存储库的“操作”选项卡中。
name: Java project - Maven Build.
on:
  workflow_dispatch:
jobs:
  maven_buil_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: show pwd
        run: pwd
      - name: show dir info
        run: ls -l
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
