name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: set-matrix
        run: echo -n "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
        if: ${{ success() }}
