name: build
on: push

env:
  DAY_OF_WEEK: Mondy

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print to Log 1
        env:
          GITHUB_CONTEXT: 'this is github context!'
        run: echo -n $GITHUB_CONTEXT
        
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Print to Log 2
        run: echo -n $DAY_OF_WEEK + ${{env.env_first_key.PROJECT_NAME}}
