name: build
on: push

env:
  DAY_OF_WEEK: Mondy

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print to Log 1
        id: var-test
        env:
          GITHUB_CONTEXT: 'this is github context!'
        ##输出环境变量失败，输出库变量成功（vars.REP_PROJECT_NAME）
        ##设置输出参数的示例
        run: |
          echo -n $GITHUB_CONTEXT $DAY_OF_WEEK + ${{env.env_first_key.PROJECT_NAME}} + ${{env.env_first_key}} + ${{env.PROJECT_NAME}} + ${{ vars.REP_PROJECT_NAME }}
          echo -n "SELECT_COLOR=red" >> "$GITHUB_OUTPUT"

      - name: Get output var - SELECT_COLOR
        env:
          SELECT_COLOR: ${{ steps.var-test.outputs.SELECT_COLOR }}
        run: |
          echo -n "SELECT_COLOR is $SELECT_COLOR"
          echo -n "steps.var-test.outputs.SELECT_COLOR is ${{ steps.var-test.outputs.SELECT_COLOR }}"
        
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Print to Log 2
        run: echo -n $GITHUB_CONTEXT $DAY_OF_WEEK + ${{vars.env_first_key.PROJECT_NAME}} + ${{vars.env_first_key}} + ${{vars.PROJECT_NAME}} + ${{ vars.REP_PROJECT_NAME }}
